name: spark
version: 0.0.1-dev
author: Chrome Team <apps-dev@chromium.org>
description: A Chrome app based development environment.
homepage: https://github.com/GoogleChrome/spark
dependencies:
  ace: '>=0.0.6+10.7.2013'
  analyzer_experimental: any
  browser: any
  chrome: any
  chrome_gen: '>=0.0.5'
  compiler_unsupported: any
  intl: any
  logging: any
  mime: any
  polymer: any
dev_dependencies:
  grinder: any
  unittest: any
