name: spark
version: 0.1.4-dev
author: Chrome Team <apps-dev@chromium.org>
description: A Chrome app based development environment.
homepage: https://github.com/GoogleChrome/spark
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ace:
    path: /Users/ericarnold/src/ace.dart
  analyzer: 0.13.0-dev.8
  archive: '>=1.0.16 <1.1.0'
  benchmark_harness: '>=1.0.4 <2.0.0'
  bignum: '>=0.0.5 <0.1.0'
  bootjack: any
  chrome: '>=0.5.3 <0.6.0'
  cipher: '>=0.6.0 <0.7.0'
  compiler_unsupported: 0.7.1
  crypto: any
  dquery: '>=0.5.0 <0.6.0'
  intl: any
  logging: any
  mime: any
  path: any
  polymer: 0.10.0-pre.4
  shadow_dom: 0.9.1
  spark_widgets:
    path: ../widgets
  tavern:
    git: https://github.com/tapted/tavern.git
    version: '>=0.0.3'
  unittest: '>=0.10.0'
  uuid: '>=0.3.0 <0.4.0'
  yaml: '>=0.9.0 <0.10.0'
dev_dependencies:
  args: any
  grinder: '>=0.5.0 <0.6.0'
dependency_overrides:
  analyzer: 0.13.0-dev.8
transformers:
- polymer:
    entry_points: web/spark_polymer.html
    csp: 'true'
