name: spark
version: 0.9.0-dev
author: Spark Team
description: A Chrome app based development environment.
homepage: https://github.com/dart-lang/spark/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ace:
    path: /Users/dev/projects/spark/ace.dart
  analyzer: '>=0.13.0 <0.14.0'
  archive: '>=1.0.16 <1.1.0'
  barback: any
  benchmark_harness: '>=1.0.4 <2.0.0'
  bignum: '>=0.0.5 <0.1.0'
  bootjack: '>=0.6.0 < 0.7.0'
  chrome: '>=0.5.3 <0.6.0'
  cipher: '>=0.7.0 <0.8.0'
  compiler_unsupported: 0.7.1
  crypto: any
  intl: any
  json: any
  logging: any
  markdown: '>=0.7.0 <0.8.0'
  mime: any
  path: any
  polymer: 0.10.0-pre.11
  spark_widgets:
    path: ../widgets
  tavern:
    git: https://github.com/tapted/tavern.git
    version: '>=0.0.5'
  unittest: '>=0.10.0'
  uuid: '>=0.3.0 <0.4.0'
  yaml: '>=0.9.0 <0.10.0'
dev_dependencies:
  args: any
  grinder: '>=0.5.0 <0.6.0'
dependency_overrides:
  barback: 0.13.0
transformers:
- polymer:
    entry_points: web/spark_polymer.html
    csp: 'true'
