name: spark
author: Chrome Team <apps-dev@chromium.org>
version: 0.1.4-dev
homepage: https://github.com/GoogleChrome/spark
description: A Chrome app based development environment.
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  ace: '>=0.1.3'
  analyzer: any
  bootjack: any
  browser: any
  chrome_gen: '>=0.3.0'
  crc32: 0.1.3
  crypto: any
  intl: any
  logging: any
  mime: any
  polymer: any
  polymer_elements:
    git: https://github.com/ErikGrimes/polymer_elements
  spark_widgets:
    path: ../widgets
  unittest: any
  uuid: any
dependency_overrides:
  path: '>=1.0.0'
dev_dependencies:
  args: any
  grinder: '>=0.4.3'
transformers:
- polymer:
    entry_points: web/spark_polymer.html
