name: spark
author: Chrome Team <apps-dev@chromium.org>
version: 0.1.4-dev
homepage: https://github.com/GoogleChrome/spark
description: A Chrome app based development environment.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ace: '>=0.1.6'
  analyzer: any
  bootjack: any
  browser: any
  chrome_gen: '>=0.3.2'
  crc32: '>=0.1.3'
  crypto: any
  dquery: 0.5.3+7
  intl: any
  logging: any
  mime: any
  path: any
  polymer: '>=0.9.2'
  spark_widgets:
    path: ../widgets
  unittest: any
  uuid: any
dev_dependencies:
  args: any
  grinder: '>=0.4.5 <0.5.0'
transformers:
- polymer:
    entry_points: web/spark_polymer.html
    csp: 'true'
