name: spark
version: 0.9.0-dev
author: The Chrome Dev Editor team
description: A Chrome app based development environment.
homepage: https://github.com/dart-lang/chromedeveditor/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ace: '>=0.5.4 <0.6.0'
  analyzer: '>=0.22.0 <0.23.0'
  archive: '>=1.0.16 <1.1.0'
  barback: any
  benchmark_harness: '>=1.0.4 <2.0.0'
  bignum: '>=0.0.5 <0.1.0'
  bower_semver:
    git: https://github.com/gaurave/bower_semver.git
    version: '>=1.0.0 <2.0.0'
  cde_polymer_designer:
    path: ../cde-polymer-designer.dart
  chrome: '>=0.6.1 <0.7.0'
  chrome_net: '>=0.1.0 <0.2.0'
  chrome_testing: '>=0.1.0 <0.2.0'
  cipher: '>=0.7.0 <0.8.0'
  compiler_unsupported: 0.7.2+1
  crc32: any
  crypto: any
  diff: '>=0.1.0 <0.2.0'
  html5lib: any
  ini: '>=1.0.0 <1.1.0'
  intl: any
  json: any
  logging: any
  markdown: '>=0.7.0 <0.8.0'
  mime: any
  paper:
    path: ../paper
  path: any
  polymer: '>=0.15.1 <0.16.0'
  quiver: '>=0.19.0 <0.20.0'
  spark_widgets:
    path: ../widgets
  stagehand: '>=0.1.2 <0.2.0'
  tavern:
    git: https://github.com/tapted/tavern.git
    version: '>=0.0.10'
  unittest: '>=0.11.0 <0.12.0'
  uuid: '>=0.4.0 <0.5.0'
  yaml: '>=1.1.0 <1.2.0'
dev_dependencies:
  args: any
  grinder: '>=0.6.0 <0.7.0'
transformers:
- polymer:
    entry_points: web/spark_polymer.html
    csp: true
