name: spark
version: 0.1.4-dev
author: Chrome Team <apps-dev@chromium.org>
description: A Chrome app based development environment.
homepage: https://github.com/GoogleChrome/spark
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ace: '>=0.3.0 <0.4.0'
  analyzer: '>=0.11.0 <0.12.0'
  archive: '>=1.0.15 <1.1.0'
  bootjack: any
  browser: any
  chrome: '>=0.5.0 <0.6.0'
  cipher: '>=0.5.0 <0.6.0'
  compiler_unsupported: 0.7.0
  crypto: any
  dquery: '>=0.5.0 <0.6.0'
  intl: any
  logging: any
  mime: any
  path: any
  polymer: '>=0.9.2'
  shadow_dom: 0.9.1
  spark_widgets:
    path: ../widgets
  tavern:
    git: git://github.com/tapted/tavern.git
  unittest: '>=0.10.0'
  uuid: any
dev_dependencies:
  args: any
  grinder: '>=0.5.0 <0.6.0'
dependency_overrides:
  analyzer: 0.11.10
transformers:
- polymer:
    entry_points: web/spark_polymer.html
    csp: 'true'
