name: spark
version: 0.0.3-dev
author: Chrome Team <apps-dev@chromium.org>
description: A Chrome app based development environment.
homepage: https://github.com/GoogleChrome/spark
dependencies:
  ace: '>=0.0.8'
  analyzer_experimental: any
  browser: any
  chrome_gen: '>=0.0.8'
  intl: any
  logging: any
  mime: any
  spark_widgets:
    path: ../widgets
dev_dependencies:
  args: any
  grinder: any
  unittest: any
