name: spark_widgets
version: 0.0.4
author: The Chrome Dev Editor Team
description: A general purpose Polymer widget library (used by Chrome Dev Editor)
homepage: https://github.com/dart-lang/chromedeveditor/tree/master/widgets
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  polymer: '>=0.15.1 <0.16.0'

dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'

transformers:
- polymer:
    entry_points:
      - example/index.html
      - example/spark_button/index.html
      - example/spark_icon/index.html
      - example/spark_menu/index.html
      - example/spark_menu_button/index.html
      - example/spark_menu_item/index.html
      - example/spark_overlay/index.html
      - example/spark_selection/index.html
      - example/spark_selector/index.html
      - example/spark_splitter/index.html
      - example/spark_split_view/index.html
      - example/spark_toggle_button/index.html
      - example/spark_toolbar/index.html
